// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl =
  "https://uydgrlouqwmibrdafegm.supabase.co";

const supabaseKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5ZGdybG91cXdtaWJyZGFmZWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjE4OTEsImV4cCI6MjA4OTgzNzg5MX0.IzFwesWlPYai61mMCfkctTaJ4lOOyZVO9LEbMLna4Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL!,
  import.meta.env.VITE_SUPABASE_ANON_KEY!
);
